root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
# full_bin = "eval $(cat .env) ; tmp/main"
full_bin = "tmp/main"
cmd = "templ generate && go build -o ./tmp/main cmd/exp/main.go"
# delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go", ".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "templ"]
include_file = []
# kill_delay = "5000ms"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 0
send_interrupt = true
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
