version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: khongtrunght
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lenslocked
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "3333:8080"
    environment:
      ADMINER_DESIGN: dracula
    depends_on:
      - db
